name: "Setup checkout and uv"
description: "Checkout main and install uv"

inputs:
  python-version:
    description: "Python version"
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        python-version: ${{ inputs.python-version }}
